{
  "hash": "a3ce1a76cd5f2e1d4f3d9315c513875f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Group 7 — ERCP trial and the Americas\"\nsubtitle: \"Studio wall\"\nauthor: \"Gandalf the Grey (Arvind) and 20 Peasants\"\nformat:\n  html:\n    toc: true\n    toc-depth: 2\ncode-tools: true\n---\n\n# Spine\n\n> Does a simple pill change post-procedure pancreatitis, who is in that trial, and where in the Americas is life long?\n\n~~This sentence stays at the top. Every panel must attach to it.~~\n\n# Introduction — the tables we own\n\nThis folder is ours for the ten days. Three tables, three shapes.\n\n- **Panel A** (`panel-A.csv`) — `medicaldata::indo_rct`: age and risk score, plus gender, treatment (`rx`: indomethacin vs placebo), and outcome.\n- **Panel B** (`panel-B.csv`) — same trial, Quals: treatment, outcome, PEP, outpatient status, site.\n- **Panel C** (`panel-C.csv`) — gapminder 2007, **Americas only**. Join by country name.\n\nThis is an RCT. `rx` is assigned, not a lifestyle. Do not talk about it as if people chose the pill.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(mosaic)\nlibrary(skimr)\nlibrary(ggformula)\n##\nlibrary(vcd) # (NEW!!) for Panel B\nlibrary(broom) # (NEW!!) for clean stat outputs\nlibrary(sf) # for Panel-C\nlibrary(rnaturalearth) # for Panel-C\n\n\nA <- read_csv(\"../../../data/group-7-ercp-and-americas/panel-A.csv\")\nB <- read_csv(\"../../../data/group-7-ercp-and-americas/panel-B.csv\")\nC <- read_csv(\"../../../data/group-7-ercp-and-americas/panel-C.csv\")\n```\n:::\n\n\n~~Found tables train the mark. A campus Free Hunch is a **made** panel of the same pair type.~~\n\n# Panel A — body / measure\n\n> *age and risk are Quant. gender, rx, outcome are Quals for split.*\n\n\n### 1. See the table\n\n~~What is a case? Which columns are Quant / Qual? What is missing?~~\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# glimpse() / inspect() / skim()\ndplyr::glimpse(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 602\nColumns: 5\n$ age     <dbl> 26, 24, 57, 29, 38, 59, 60, 29, 53, 20, 51, 19, 57, 44, 33, 46…\n$ risk    <dbl> 2.0, 1.0, 1.0, 2.0, 3.5, 3.0, 1.5, 1.0, 2.0, 2.0, 3.0, 2.5, 1.…\n$ gender  <chr> \"female\", \"male\", \"female\", \"female\", \"female\", \"female\", \"fem…\n$ rx      <chr> \"indomethacin\", \"placebo\", \"placebo\", \"placebo\", \"indomethacin…\n$ outcome <chr> \"yes\", \"no\", \"no\", \"yes\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", …\n```\n\n\n:::\n:::\n\nMy Panel-A data has:\n\n  - 602 observations and 5 variables.\n  - `age`: Quantitative, numeric\n  - `risk`: Quantitative, numeric\n  - `gender`: Qualitative, categorical. Encoded <chr>, to be mutated\n  - `rx`: Qualitative, categorical. Encoded <chr>, to be mutated\n  - `outcome`: Qualitative, categorical. Encoded <chr>, to be mutated\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# glimpse() / inspect() / skim()\nskimr::skim(A)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |     |\n|:------------------------|:----|\n|Name                     |A    |\n|Number of rows           |602  |\n|Number of columns        |5    |\n|_______________________  |     |\n|Column type frequency:   |     |\n|character                |3    |\n|numeric                  |2    |\n|________________________ |     |\n|Group variables          |None |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|gender        |         0|             1|   4|   6|     0|        2|          0|\n|rx            |         0|             1|   7|  12|     0|        2|          0|\n|outcome       |         0|             1|   2|   3|     0|        2|          0|\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  mean|    sd| p0|  p25|  p50| p75| p100|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|--:|----:|----:|---:|----:|:-----|\n|age           |         0|             1| 45.27| 13.30| 19| 35.0| 45.0|  54| 90.0|▅▇▇▃▁ |\n|risk          |         0|             1|  2.38|  0.88|  1|  1.5|  2.5|   3|  5.5|▅▇▃▁▁ |\n\n\n:::\n:::\n\n\n\nFurthermore, on the Qual variables panel-A data has : \n\n- `gender` has 2 levels: \"male\" and \"female\"\n- `rx` has 2 levels: \"indomethacin\" and \"placebo\"\n- `outcome` has 2 levels: \"no\" and \"yes\"\n\nAnd on the Quant variables panel-A data has :\n\n- `age` has a mean of 45.26, sd of 13.2, median of 45, min of 19, and max of 90\n- `risk` has a mean of 2.38, sd of 0.88, median of 2.5, min of 1, and max of 5.5\n\nThere is no missing data. `age` histogram shown in `skim()` output seems skewed to the right; `risk` is slightly skewed right / normal. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nA_mod <- A |> \n  mutate(\n    gender = as.factor(gender),\n    rx = as.factor(rx),\n    outcome = as.factor(outcome)\n  )\n\nglimpse(A_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 602\nColumns: 5\n$ age     <dbl> 26, 24, 57, 29, 38, 59, 60, 29, 53, 20, 51, 19, 57, 44, 33, 46…\n$ risk    <dbl> 2.0, 1.0, 1.0, 2.0, 3.5, 3.0, 1.5, 1.0, 2.0, 2.0, 3.0, 2.5, 1.…\n$ gender  <fct> female, male, female, female, female, female, female, male, ma…\n$ rx      <fct> indomethacin, placebo, placebo, placebo, indomethacin, placebo…\n$ outcome <fct> yes, no, no, yes, no, no, no, no, no, no, no, yes, no, no, no,…\n```\n\n\n:::\n:::\n\nAll ready now. \n\n\n### 2. Ask\n\n~~One question *this* table can answer. One it cannot. Write both.~~\nLooking at the overall Spine statement, I can pose the following Questions:\n\nPossibly can answer: \n\n1. Are the dataset balanced by `gender` and by `rx` (assigned medication)?\n1. What are the distributions for each of the Quant variables, `age`, and `risk`?\n1. How are they different based on the Qual variables? (e.g., is there a difference in age distribution between `gender`-s, or between `rx` groups?)\n1. Is the `risk` different for men and women? (`Main Character` Question)\n\nPossibly cannot answer:\n\n1. Does the medication efficacy depend upon dosage? ( No `dosage` variable.)\n1. Better than some other medicine? ( No data, need an entire new table)\n\n\n### 3. Choose a mark\n\n~~Geom, map mark, or (later) test that matches the pair type. Name it before you code.~~\n\n1. A bar chart\n2. Histograms\n3. Histograms, coloured by `gender` and `rx`\n4. Histogram?? AND Stat Test For Means?? (NEW!!)\n\n### 4. Predict\n\n~~What do we think we will see? One sentence, before Run.~~\n\nI think we will see that there is a difference in `risk` between men and women. \n\nAnd a Stat test for means will confirm this.\n\n### 5. Make\n\n~~Human brick first. Optional: one AI prompt, pasted below, only for what section 3 named.~~\n\nThese first few charts are what I want to check out. I may/will not have these charts in the final rendered Quarto, but want to comment on findings if needed. \n\nIf any chart is surprising, it stays. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Question 1\nA_mod |> gf_bar(~ gender)\n\n## Question 2\nA_mod |> gf_bar(~ rx)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Question 3\nA_mod |> gf_histogram(~ age)\nA_mod |> gf_histogram(~ age, fill = ~ gender)\nA |> gf_histogram(~ age, fill = ~ rx)\n##\nA_mod |> gf_histogram(~ risk)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Question #4 (Main Character)\n\nA_mod |> gf_histogram(~ risk, fill = ~ gender)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/panel-A-Main-Character-question-1.png){width=2100}\n:::\n\n```{.r .cell-code}\nA_mod |> gf_density(~ risk, fill = ~ gender)\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/panel-A-Main-Character-question-2.png){width=2100}\n:::\n:::\n\n\nThere are more `women` than `men` in the sample. \n\nDistributions do change with `gender`. But hard to say outright from the overlapping histograms. *Densities* for `risk` look different for men and women, though. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Main Character Question\n\nmosaic::t.test(risk ~ gender, data = A_mod) |> broom::tidy()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"estimate\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"estimate1\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"estimate2\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"parameter\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.low\"],\"name\":[7],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.high\"],\"name\":[8],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"method\"],\"name\":[9],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"alternative\"],\"name\":[10],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"0.3014706\",\"2\":\"2.444328\",\"3\":\"2.142857\",\"4\":\"3.386018\",\"5\":\"0.0008600262\",\"6\":\"191.9831\",\"7\":\"0.1258602\",\"8\":\"0.4770809\",\"9\":\"Welch Two Sample t-test\",\"10\":\"two.sided\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n### 6. Say\n\n~~Caption + one sentence we will stand behind.~~\n\n\n1. Women are literally at higher `risk` than men for post-procedure pancreatitis, no cap. It’s giving sad energy. \n2. Difference in mean `risk` between them is $0.3014706$, statistically significant (p-value < 0.05).\n\n### 7. Limit\n\n~~What this panel cannot do.~~\n\nWe’re assuming the community here is not specifically linked with pancreatitis. Would this `risk` be similar in other communities? (Lowkey assuming this community isn’t pancreatitis-coded. Would the risk vibe be similar in other communities, no cap?)\n\n# Panel B — category / talk\n\n*rx × outcome is the trial mosaic. site × outcome. Do not average rx.*\n\n\n### 1. See the table\n\n~~What is a case? Which columns are Quant / Qual? What is missing?~~\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# glimpse() / inspect() / skim()\ndplyr::glimpse(B)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 602\nColumns: 7\n$ gender  <chr> \"female\", \"male\", \"female\", \"female\", \"female\", \"female\", \"fem…\n$ rx      <chr> \"indomethacin\", \"placebo\", \"placebo\", \"placebo\", \"indomethacin…\n$ outcome <chr> \"yes\", \"no\", \"no\", \"yes\", \"no\", \"no\", \"no\", \"no\", \"no\", \"no\", …\n$ pep     <chr> \"no\", \"yes\", \"no\", \"no\", \"yes\", \"no\", \"no\", \"no\", \"no\", \"no\", …\n$ status  <chr> \"outpatient\", \"outpatient\", \"outpatient\", \"outpatient\", \"inpat…\n$ type    <chr> \"1_type 1\", \"0_no SOD\", \"2_type 2\", \"1_type 1\", \"1_type 1\", \"1…\n$ site    <chr> \"1_UM\", \"1_UM\", \"1_UM\", \"1_UM\", \"1_UM\", \"1_UM\", \"1_UM\", \"1_UM\"…\n```\n\n\n:::\n:::\n\nMy Panel-B data has:\n\n- 602 observations and 5 variables.\n- `rx`: Qualitative, categorical. Encoded <chr>, to be mutated\n- `outcome`: Qualitative, categorical. Encoded <chr>, to be mutated\n- `pep`: Qualitative, categorical. Encoded <chr>, to be mutated\n- `status`: Qualitative, categorical. Encoded <chr>, to be mutated\n- `type`: Qualitative, categorical. Encoded <chr>, to be mutated\n- `site`: Qualitative, categorical. Encoded <chr>, to be mutated\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# glimpse() / inspect() / skim()\nskimr::skim(B)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |     |\n|:------------------------|:----|\n|Name                     |B    |\n|Number of rows           |602  |\n|Number of columns        |7    |\n|_______________________  |     |\n|Column type frequency:   |     |\n|character                |7    |\n|________________________ |     |\n|Group variables          |None |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min| max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|---:|-----:|--------:|----------:|\n|gender        |         0|             1|   4|   6|     0|        2|          0|\n|rx            |         0|             1|   7|  12|     0|        2|          0|\n|outcome       |         0|             1|   2|   3|     0|        2|          0|\n|pep           |         0|             1|   2|   3|     0|        2|          0|\n|status        |         0|             1|   9|  10|     0|        2|          0|\n|type          |         0|             1|   8|   8|     0|        4|          0|\n|site          |         0|             1|   4|   6|     0|        4|          0|\n\n\n:::\n:::\n\n\nFurther, on the Qual variables panel-B data has : \n\n- `gender` has 2 levels: \"male\" and \"female\"\n- `rx` has 2 levels: \"indomethacin\" and \"placebo\"\n- `outcome` has 2 levels: \"no\" and \"yes\"\n- `pep` has 2 levels: \"no\" and \"yes\"\n- `status` has 2 levels: \"outpatient\" and \"inpatient\"\n- `type` has 4 levels: to be listed\n- `site` has 4 levels: to be listed\n\nAnd on the Quant variables panel-A data has : None. All variable are Qualitative only. \n\nThere is no missing data.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB_mod <- B |> \n  mutate(across(where(is.character), as.factor)) # Whoa!!\n\nglimpse(B_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 602\nColumns: 7\n$ gender  <fct> female, male, female, female, female, female, female, male, ma…\n$ rx      <fct> indomethacin, placebo, placebo, placebo, indomethacin, placebo…\n$ outcome <fct> yes, no, no, yes, no, no, no, no, no, no, no, yes, no, no, no,…\n$ pep     <fct> no, yes, no, no, yes, no, no, no, no, no, no, no, no, no, no, …\n$ status  <fct> outpatient, outpatient, outpatient, outpatient, inpatient, inp…\n$ type    <fct> 1_type 1, 0_no SOD, 2_type 2, 1_type 1, 1_type 1, 1_type 1, 0_…\n$ site    <fct> 1_UM, 1_UM, 1_UM, 1_UM, 1_UM, 1_UM, 1_UM, 1_UM, 1_UM, 1_UM, 1_…\n```\n\n\n:::\n:::\n\n\nNow, we're ready.\n\n### 2. Ask\n\n~~One question *this* table can answer. One it cannot. Write both.~~\n\nLooking at the spine statement again, I can pose the following Questions:\n\nPossibly can answer:\n\n1. Are the dataset balanced by all Qual variables, except the measured one (`output`) ?\n1. Are there differences in *how the medication was administered* ( i.e.`rx`)  across `gender`, `pep`, `site` or `type` of patient? ( Just curious. Does this matter? Need to ask the expert who did this research.)\n1. Does the medication work? (Main Character Question)\n1. Does it work differently for men and for women? ( Possible Main Character Question)\n\nPossibly cannot answer:\n\n1. Does the medication efficacy depend upon dosage? ( No `dosage` variable.)\n\n### 3. Choose a mark\n\n1. Bar Chart\n1. Bar Chart with fill or facet\n1. Mosaic Chart (NEW!!)\n1.  Mosaic Chart again??\n\n### 4. Predict\n\n~~What do we think we will see? One sentence, before Run.~~\n\nA well-balanced RCT experiment, balanced across all `factors` such as `gender`, `pep`, `site`, and `type`. \n\nI think the medicine might show as working in this experiment. \n\n### 5. Make\n\n~~Human brick first. Optional: one AI prompt, pasted below, only for what section 3 named.~~\n\nThese first few charts are what I want to check out. I will not have these charts in the final rendered Quarto, but comment on findings. \n\nIf any is surprising, it stays. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Question 1\nB_mod |> gf_bar(~ gender)\nB_mod |> gf_bar(~ rx)\nB_mod |> gf_bar(~ pep)\nB_mod |> gf_bar(~ status)\nB_mod |> gf_bar(~ type)\nB_mod |> gf_bar(~ site)\n```\n:::\n\n- `gender`: More women than men\n- ` rx`: Medication and placebo prescribed to equal numbers. Fair. \n- All other factors have imbalanced counts. It is what it is. \n\n::: {.cell}\n\n```{.r .cell-code}\n## Question 2\nB_mod |> gf_bar(~ gender, fill = ~ rx)\nB_mod |> gf_bar(~ pep, fill = ~ rx)\nB_mod |> gf_bar(~ status, fill = ~ rx)\nB_mod |> gf_bar(~ type, fill = ~ rx)\nB_mod |> gf_bar(~ site, fill = ~ rx)\n```\n:::\n\nAll kinds of people, based on ***each of the factors*** are EQUALLY divided between `indomethacin` and `placebo`. Superb experiment design!! Waah, waah!!\n\nNOTE: this can be visually confirmed by using `gf_props` for all code lines in the preceding chunk. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question #3\n# library(vcd) # Put this in the setup chunk above!\n# \nB_table <- vcd::structable(outcome ~ rx, data = B_mod)\nB_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             outcome  no yes\nrx                          \nindomethacin         268  27\nplacebo              255  52\n```\n\n\n:::\n\n```{.r .cell-code}\n# Main Character Question\nvcd::mosaic(B_table, shade = TRUE, main = \"Mosaic Chart for Indomethacin RCT\")\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/main-character-question-B-1.png){width=2100}\n:::\n:::\n\n\n\n### 6. Say\n\n~~Caption + one sentence we will stand behind.~~\n\nThe mosaic plot’s saying there’s a significant diff between `indomethacin` and `placebo` performance. But plot twist: the diff is wrong-sided: placebo’s actually slaying. Main character `indomethacin` is kinda flopping compared to placebo. Low-key mid, high-key not it. We need a new main. \n\n### 7. Limit\n\n~~What this panel cannot do.~~\n\nI cannot say whether this trial would show similar results if conducted in another community. I presume the experimenters thought of this beforehand. \n\n\n# Panel C — place\n\n*Americas-only lifeExp / gdpPercap / pop. Same join brick as other map panels.*\n\n```r\n# library(sf)\n# library(rnaturalearth)\n# world <- ne_countries(scale = \"medium\", returnclass = \"sf\")\n```\n\n\n### 1. See the table\n\nWhat is a case? Which columns are Quant / Qual? What is missing?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# glimpse() / inspect() / skim()\ndplyr::glimpse(C)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 25\nColumns: 6\n$ country   <chr> \"Argentina\", \"Bolivia\", \"Brazil\", \"Canada\", \"Chile\", \"Colomb…\n$ continent <chr> \"Americas\", \"Americas\", \"Americas\", \"Americas\", \"Americas\", …\n$ year      <dbl> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, …\n$ lifeExp   <dbl> 75.320, 65.554, 72.390, 80.653, 78.553, 72.889, 78.782, 78.2…\n$ pop       <dbl> 40301927, 9119152, 190010647, 33390141, 16284741, 44227550, …\n$ gdpPercap <dbl> 12779.380, 3822.137, 9065.801, 36319.235, 13171.639, 7006.58…\n```\n\n\n:::\n:::\n\nMy Panel-C data has:\n\n- 25 rows and 6 columns.\n- `country`: Qualitative, categorical. Encoded <chr>, to be mutated\n- `continent`: Qualitative, categorical. Encoded <chr>, to be mutated\n- `year`: Quantitative, numeric. Looks like it is just 2007 right through and data is for one year only. \n- `lifeExp`: Quantitative, numeric\n- `pop`: Quantitative, numeric\n- `gdpPercap`: Quantitative, numeric\n\nLet us `join` this data with map geometries from `rnaturalearth`, so that we can make a map to show off the status in 2007. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# library(sf) ( Add this into setup chunk above!)\n# library(rnaturalearth)\nworld <- rnaturalearth::ne_countries(scale = \"medium\", returnclass = \"sf\")\nglimpse(world)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 242\nColumns: 169\n$ featurecla <chr> \"Admin-0 country\", \"Admin-0 country\", \"Admin-0 country\", \"A…\n$ scalerank  <int> 1, 1, 1, 3, 5, 6, 1, 1, 1, 3, 5, 3, 3, 3, 3, 1, 5, 3, 3, 3,…\n$ labelrank  <int> 3, 3, 3, 2, 3, 6, 4, 3, 4, 6, 6, 6, 6, 6, 4, 5, 2, 4, 5, 6,…\n$ sovereignt <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ sov_a3     <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_dif   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1,…\n$ level      <int> 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,…\n$ type       <chr> \"Sovereign country\", \"Sovereign country\", \"Sovereign countr…\n$ tlc        <chr> \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1\", \"1\",…\n$ admin      <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ adm0_a3    <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ geou_dif   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ geounit    <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ gu_a3      <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ su_dif     <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ subunit    <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ su_a3      <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ brk_diff   <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,…\n$ name       <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ name_long  <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ brk_a3     <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ brk_name   <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ brk_group  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ abbrev     <chr> \"Zimb.\", \"Zambia\", \"Yem.\", \"Viet.\", \"Ven.\", \"Vat.\", \"Van.\",…\n$ postal     <chr> \"ZW\", \"ZM\", \"YE\", \"VN\", \"VE\", \"V\", \"VU\", \"UZ\", \"UY\", \"FSM\",…\n$ formal_en  <chr> \"Republic of Zimbabwe\", \"Republic of Zambia\", \"Republic of …\n$ formal_fr  <chr> NA, NA, NA, NA, \"República Bolivariana de Venezuela\", NA, N…\n$ name_ciawf <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Hol…\n$ note_adm0  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, \"U.S.A.\", \"U.S.…\n$ note_brk   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ name_sort  <chr> \"Zimbabwe\", \"Zambia\", \"Yemen, Rep.\", \"Vietnam\", \"Venezuela,…\n$ name_alt   <chr> NA, NA, NA, NA, NA, \"Holy See\", NA, NA, NA, NA, NA, NA, NA,…\n$ mapcolor7  <int> 1, 5, 5, 5, 1, 1, 6, 2, 1, 5, 2, 4, 4, 4, 4, 4, 4, 6, 6, 6,…\n$ mapcolor8  <int> 5, 8, 3, 6, 3, 3, 3, 3, 2, 2, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6,…\n$ mapcolor9  <int> 3, 5, 3, 5, 1, 4, 7, 5, 2, 4, 5, 1, 1, 1, 1, 1, 1, 6, 6, 6,…\n$ mapcolor13 <int> 9, 13, 11, 4, 4, 2, 3, 4, 10, 13, 3, 1, 1, 1, 1, 1, 1, 3, 3…\n$ pop_est    <dbl> 14645468, 17861030, 29161922, 96462106, 28515829, 825, 2998…\n$ pop_rank   <int> 14, 14, 15, 16, 15, 2, 10, 15, 12, 9, 8, 8, 9, 9, 8, 12, 17…\n$ pop_year   <int> 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019, 2019,…\n$ gdp_md     <int> 21440, 23309, 22581, 261921, 482359, -99, 934, 57921, 56045…\n$ gdp_year   <int> 2019, 2019, 2019, 2019, 2014, 2019, 2019, 2019, 2019, 2018,…\n$ economy    <chr> \"5. Emerging region: G20\", \"7. Least developed region\", \"7.…\n$ income_grp <chr> \"5. Low income\", \"4. Lower middle income\", \"4. Lower middle…\n$ fips_10    <chr> \"ZI\", \"ZA\", \"YM\", \"VM\", \"VE\", \"VT\", \"NH\", \"UZ\", \"UY\", \"FM\",…\n$ iso_a2     <chr> \"ZW\", \"ZM\", \"YE\", \"VN\", \"VE\", \"VA\", \"VU\", \"UZ\", \"UY\", \"FM\",…\n$ iso_a2_eh  <chr> \"ZW\", \"ZM\", \"YE\", \"VN\", \"VE\", \"VA\", \"VU\", \"UZ\", \"UY\", \"FM\",…\n$ iso_a3     <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ iso_a3_eh  <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ iso_n3     <chr> \"716\", \"894\", \"887\", \"704\", \"862\", \"336\", \"548\", \"860\", \"85…\n$ iso_n3_eh  <chr> \"716\", \"894\", \"887\", \"704\", \"862\", \"336\", \"548\", \"860\", \"85…\n$ un_a3      <chr> \"716\", \"894\", \"887\", \"704\", \"862\", \"336\", \"548\", \"860\", \"85…\n$ wb_a2      <chr> \"ZW\", \"ZM\", \"RY\", \"VN\", \"VE\", \"-99\", \"VU\", \"UZ\", \"UY\", \"FM\"…\n$ wb_a3      <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"-99\", \"VUT\", \"UZB\", \"UR…\n$ woe_id     <int> 23425004, 23425003, 23425002, 23424984, 23424982, 23424986,…\n$ woe_id_eh  <int> 23425004, 23425003, 23425002, 23424984, 23424982, 23424986,…\n$ woe_note   <chr> \"Exact WOE match as country\", \"Exact WOE match as country\",…\n$ adm0_iso   <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_diff  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ adm0_tlc   <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_us <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_fr <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_ru <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_es <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_cn <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_tw <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_in <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_np <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_pk <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_de <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_gb <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_br <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_il <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_ps <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_sa <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_eg <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_ma <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_pt <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_ar <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_jp <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_ko <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_vn <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_tr <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_id <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_pl <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_gr <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_it <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_nl <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_se <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_bd <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_ua <chr> \"ZWE\", \"ZMB\", \"YEM\", \"VNM\", \"VEN\", \"VAT\", \"VUT\", \"UZB\", \"UR…\n$ adm0_a3_un <int> -99, -99, -99, -99, -99, -99, -99, -99, -99, -99, -99, -99,…\n$ adm0_a3_wb <int> -99, -99, -99, -99, -99, -99, -99, -99, -99, -99, -99, -99,…\n$ continent  <chr> \"Africa\", \"Africa\", \"Asia\", \"Asia\", \"South America\", \"Europ…\n$ region_un  <chr> \"Africa\", \"Africa\", \"Asia\", \"Asia\", \"Americas\", \"Europe\", \"…\n$ subregion  <chr> \"Eastern Africa\", \"Eastern Africa\", \"Western Asia\", \"South-…\n$ region_wb  <chr> \"Sub-Saharan Africa\", \"Sub-Saharan Africa\", \"Middle East & …\n$ name_len   <int> 8, 6, 5, 7, 9, 7, 7, 10, 7, 10, 12, 14, 15, 4, 14, 11, 24, …\n$ long_len   <int> 8, 6, 5, 7, 9, 7, 7, 10, 7, 30, 16, 24, 28, 4, 14, 11, 13, …\n$ abbrev_len <int> 5, 6, 4, 5, 4, 4, 4, 4, 4, 6, 6, 6, 11, 4, 9, 4, 6, 10, 6, …\n$ tiny       <int> -99, -99, -99, 2, -99, 4, 2, 5, -99, -99, 2, 3, 3, 2, 3, -9…\n$ homepart   <int> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, -99, -99, -99, -99, -99, 1…\n$ min_zoom   <dbl> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,…\n$ min_label  <dbl> 2.5, 3.0, 3.0, 2.0, 2.5, 5.0, 4.0, 3.0, 3.0, 5.0, 5.0, 5.0,…\n$ max_label  <dbl> 8.0, 8.0, 8.0, 7.0, 7.5, 10.0, 9.0, 8.0, 8.0, 10.0, 10.0, 1…\n$ label_x    <dbl> 29.92544, 26.39530, 45.87438, 105.38729, -64.59938, 12.4534…\n$ label_y    <dbl> -18.911640, -14.660804, 15.328226, 21.715416, 7.182476, 41.…\n$ ne_id      <dbl> 1159321441, 1159321439, 1159321425, 1159321417, 1159321411,…\n$ wikidataid <chr> \"Q954\", \"Q953\", \"Q805\", \"Q881\", \"Q717\", \"Q237\", \"Q686\", \"Q2…\n$ name_ar    <chr> \"زيمبابوي\", \"زامبيا\", \"اليمن\", \"فيتنام\", \"فنزويلا\", \"الفاتي…\n$ name_bn    <chr> \"জিম্বাবুয়ে\", \"জাম্বিয়া\", \"ইয়েমেন\", \"ভিয়েতনাম\", \"ভেনেজুয়েলা\", \"ভ্যাটিকান সিটি\", \"ভানুয়াতু\",…\n$ name_de    <chr> \"Simbabwe\", \"Sambia\", \"Jemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ name_en    <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ name_es    <chr> \"Zimbabue\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Ciu…\n$ name_fa    <chr> \"زیمبابوه\", \"زامبیا\", \"یمن\", \"ویتنام\", \"ونزوئلا\", \"واتیکان\"…\n$ name_fr    <chr> \"Zimbabwe\", \"Zambie\", \"Yémen\", \"Viêt Nam\", \"Venezuela\", \"Ci…\n$ name_el    <chr> \"Ζιμπάμπουε\", \"Ζάμπια\", \"Υεμένη\", \"Βιετνάμ\", \"Βενεζουέλα\", …\n$ name_he    <chr> \"זימבבואה\", \"זמביה\", \"תימן\", \"וייטנאם\", \"ונצואלה\", \"קריית ה…\n$ name_hi    <chr> \"ज़िम्बाब्वे\", \"ज़ाम्बिया\", \"यमन\", \"वियतनाम\", \"वेनेज़ुएला\", \"वैटिकन नगर\", \"वानूआटू\", …\n$ name_hu    <chr> \"Zimbabwe\", \"Zambia\", \"Jemen\", \"Vietnám\", \"Venezuela\", \"Vat…\n$ name_id    <chr> \"Zimbabwe\", \"Zambia\", \"Yaman\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ name_it    <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Cit…\n$ name_ja    <chr> \"ジンバブエ\", \"ザンビア\", \"イエメン\", \"ベトナム\", \"ベネズエラ\", \"バチカン\", \"バヌアツ\", \"…\n$ name_ko    <chr> \"짐바브웨\", \"잠비아\", \"예멘\", \"베트남\", \"베네수엘라\", \"바티칸 시국\", \"바누아투\", \"우즈베…\n$ name_nl    <chr> \"Zimbabwe\", \"Zambia\", \"Jemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ name_pl    <chr> \"Zimbabwe\", \"Zambia\", \"Jemen\", \"Wietnam\", \"Wenezuela\", \"Wat…\n$ name_pt    <chr> \"Zimbábue\", \"Zâmbia\", \"Iémen\", \"Vietname\", \"Venezuela\", \"Va…\n$ name_ru    <chr> \"Зимбабве\", \"Замбия\", \"Йемен\", \"Вьетнам\", \"Венесуэла\", \"Ват…\n$ name_sv    <chr> \"Zimbabwe\", \"Zambia\", \"Jemen\", \"Vietnam\", \"Venezuela\", \"Vat…\n$ name_tr    <chr> \"Zimbabve\", \"Zambiya\", \"Yemen\", \"Vietnam\", \"Venezuela\", \"Va…\n$ name_uk    <chr> \"Зімбабве\", \"Замбія\", \"Ємен\", \"В'єтнам\", \"Венесуела\", \"Вати…\n$ name_ur    <chr> \"زمبابوے\", \"زیمبیا\", \"یمن\", \"ویتنام\", \"وینیزویلا\", \"ویٹیکن …\n$ name_vi    <chr> \"Zimbabwe\", \"Zambia\", \"Yemen\", \"Việt Nam\", \"Venezuela\", \"Th…\n$ name_zh    <chr> \"津巴布韦\", \"赞比亚\", \"也门\", \"越南\", \"委内瑞拉\", \"梵蒂冈\", \"瓦努阿图\", \"乌兹别克斯坦\",…\n$ name_zht   <chr> \"辛巴威\", \"尚比亞\", \"葉門\", \"越南\", \"委內瑞拉\", \"梵蒂岡\", \"萬那杜\", \"烏茲別克\", \"烏拉…\n$ fclass_iso <chr> \"Admin-0 country\", \"Admin-0 country\", \"Admin-0 country\", \"A…\n$ tlc_diff   <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_tlc <chr> \"Admin-0 country\", \"Admin-0 country\", \"Admin-0 country\", \"A…\n$ fclass_us  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_fr  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_ru  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_es  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_cn  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_tw  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_in  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_np  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_pk  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_de  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_gb  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_br  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_il  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_ps  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_sa  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_eg  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_ma  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_pt  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_ar  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_jp  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_ko  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_vn  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_tr  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_id  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_pl  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_gr  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_it  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_nl  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_se  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_bd  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ fclass_ua  <chr> NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…\n$ geometry   <MULTIPOLYGON [°]> MULTIPOLYGON (((31.28789 -2..., MULTIPOLYGON (…\n```\n\n\n:::\n:::\n\n\n`world` is an `sf` data frame, with a MULTIPOLYGON `geometry` column, which we need. It has 177 rows and 64 columns. \n\nThe `name` column has the name of the country, which is what we will use to `join` with our Panel-C data.\n\nLet us select just the `name` and `geometry` columns first, and then join with panel-C data. In passing, we will also mutate `country` and `continent` into factors.\n\nNOTE: this method fails for the USA, since panel-C describes that country as \"United States\" and world as \"United States of America\". We will make the change in Panel-C, before joining:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nworld_selected <- world |> dplyr::select(name, geometry)\nC_mod <- C |>\n  ###\n  mutate(country = str_replace(\n    string = country,\n    pattern = \"United States\",\n    replacement = \"United States of America\"\n  )) |>\n  ###\n  left_join(world_selected, by = c(\"country\" = \"name\")) |>\n  ###\n  mutate(\n    country = as_factor(country),\n    continent = as_factor(continent)\n  ) |>\n  ###\n  st_as_sf() # Convert to sf object, just to be careful\nglimpse(C_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 25\nColumns: 7\n$ country   <fct> Argentina, Bolivia, Brazil, Canada, Chile, Colombia, Costa R…\n$ continent <fct> Americas, Americas, Americas, Americas, Americas, Americas, …\n$ year      <dbl> 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, …\n$ lifeExp   <dbl> 75.320, 65.554, 72.390, 80.653, 78.553, 72.889, 78.782, 78.2…\n$ pop       <dbl> 40301927, 9119152, 190010647, 33390141, 16284741, 44227550, …\n$ gdpPercap <dbl> 12779.380, 3822.137, 9065.801, 36319.235, 13171.639, 7006.58…\n$ geometry  <MULTIPOLYGON [°]> MULTIPOLYGON (((-57.60889 -..., MULTIPOLYGON ((…\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskimr::skim(C_mod)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning: Couldn't find skimmers for class: sfc_MULTIPOLYGON, sfc; No\nuser-defined `sfl` provided. Falling back to `character`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |      |\n|:------------------------|:-----|\n|Name                     |C_mod |\n|Number of rows           |25    |\n|Number of columns        |7     |\n|_______________________  |      |\n|Column type frequency:   |      |\n|character                |1     |\n|factor                   |2     |\n|numeric                  |4     |\n|________________________ |      |\n|Group variables          |None  |\n\n\n**Variable type: character**\n\n|skim_variable | n_missing| complete_rate| min|    max| empty| n_unique| whitespace|\n|:-------------|---------:|-------------:|---:|------:|-----:|--------:|----------:|\n|geometry      |         0|             1|   6| 390722|     0|       25|          0|\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                     |\n|:-------------|---------:|-------------:|:-------|--------:|:------------------------------|\n|country       |         0|             1|FALSE   |       25|Arg: 1, Bol: 1, Bra: 1, Can: 1 |\n|continent     |         0|             1|FALSE   |        1|Ame: 25                        |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|        mean|          sd|         p0|        p25|       p50|         p75|         p100|hist  |\n|:-------------|---------:|-------------:|-----------:|-----------:|----------:|----------:|---------:|-----------:|------------:|:-----|\n|year          |         0|             1|     2007.00|        0.00|    2007.00|    2007.00|    2007.0|     2007.00|      2007.00|▁▁▇▁▁ |\n|lifeExp       |         0|             1|       73.61|        4.44|      60.92|      71.75|      72.9|       76.38|        80.65|▁▁▇▇▅ |\n|pop           |         0|             1| 35954847.36| 68833781.19| 1056608.00| 5675356.00| 9319622.0| 28674757.00| 301139947.00|▇▁▁▁▁ |\n|gdpPercap     |         0|             1|    11003.03|     9713.21|    1201.64|    5728.35|    8948.1|    11977.57|     42951.65|▇▃▁▁▁ |\n\n\n:::\n:::\n\n\nFinally, after joining, on the Qual variables panel-C data has :\n\n- `country`: Qualitative, categorical. Encoded <fct> with 25 levels: \"Argentina\", \"Bolivia\", \"Brazil\", \"Canada\", \"Chile\", \"Colombia\", \"Costa Rica\", \"Cuba\", \"Dominican Republic\", \"Ecuador\", \"El Salvador\", \"French Guiana\", \"Guatemala\", \"Guyana\", \"Haiti\", \"Honduras\", \"Jamaica\", \"Mexico\", \"Nicaragua\", \"Panama\", \"Paraguay\", \"Peru\", \"Suriname\", \"Trinidad and Tobago\", and \"United States\".\n- `continent`: Qualitative, categorical. Encoded <fct> with 1 level: \"Americas\"\n\nAnd the Quant variables are: \n\n- `year`: Quantitative, numeric. Encoded <dbl> with 1 level: 2007\n- `lifeExp`: Quantitative, numeric. Mean: $7.360812e+01$, sd: $4.440948e+00$, min: $60.916$\t, median: $72.899$, max:  $80.65$\n- `pop`: Quantitative, numeric.Mean: $3.595485e+07$, sd: $6.883378e+07$, min: $1056608.000$\t, median: $9319622.000$, max:  $3.011399e+08$\n- `gdpPercap`: Quantitative, numeric. Mean: $1.100303e+04$, sd: $9.713209e+03$, min: $1201.637$\t, median: $8948.103$, max:  $4.295165e+04$\n\nThere is no missing data. Histograms shown in `skim()` output are extremely right-skewed for `pop` and `gdpPercap`!! \n\n### 2. Ask\n\n~~One question *this* table can answer. One it cannot. Write both.~~\n\nBased on the Spine, I can pose the following Questions:\n\nPossibly can answer:\n\n1. How are the Quant variables distributed?\n1. Are `gdpPercap` and`lifeExp` correlated across the Americas? (Main Character Question)\n2. How do the quantities `gdpPercap`, `lifeExp`, and `pop` vary across the Americas? (Also Main Character Question)\n\nPossibly cannot answer:\n\n1. Does global trade / wars affect longevity? ( No data)\n2. Do the quant variables vary over time? ( Data is only for 2007)\n\n### 3. Choose a mark\n\n~~Geom, map mark, or (later) test that matches the pair type. Name it before you code.~~\n\n1. Scatter Plot + Correlation Test (NEW!!)\n2. Maps ( NEW!!)\n\n### 4. Predict\n\n~~What do we think we will see? One sentence, before Run.~~\n\n1. I think `lifeExp` is correlated positively with `gdpPercap. \n2. The map will show stark variation in each of the quantities across the Americas, since there are poor-er countries there like say in Latin America, and then there are US and Canada. \n\n### 5. Make\n\n~Human brick first. Optional: one AI prompt, pasted below, only for what section 3 named.~\n\n\n::: {.cell}\n\n```{.r .cell-code}\nC_mod |> gf_histogram(~ lifeExp)\nC_mod |> gf_histogram(~ pop)\nC_mod |> gf_histogram(~ gdpPercap)\n```\n:::\n\n\nAs expected(?) `lifeExp` is skewed left, and `pop` and `gdpPercap` are skewed right!!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question #2\nC_mod |> gf_point(lifeExp ~ gdpPercap) |> \n  gf_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/main-character-question-C-1-1.png){width=2100}\n:::\n\n```{.r .cell-code}\nmosaic::cor.test(lifeExp ~ gdpPercap, \n                 data = C_mod) |> \n  broom::tidy()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"estimate\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"parameter\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"conf.low\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.high\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"method\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"alternative\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"0.5909661\",\"2\":\"3.51331\",\"3\":\"0.001866495\",\"4\":\"23\",\"5\":\"0.2554958\",\"6\":\"0.7994243\",\"7\":\"Pearson's product-moment correlation\",\"8\":\"two.sided\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question #3\n\nC_mod |> gf_sf(geometry = ~ geometry, fill = ~ gdpPercap) |>\n  gf_refine(\n    coord_sf(\n      xlim = c(-170, -30),  # longitude: 170°W to 30°W\n      ylim = c(-60, 85),    # latitude: South to North America\n      expand = FALSE\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/main-character-question-C-2-1.png){width=2100}\n:::\n\n```{.r .cell-code}\nC_mod |> gf_sf(geometry = ~ geometry, fill = ~ lifeExp) |>\n  gf_refine(\n    coord_sf(\n      xlim = c(-170, -30),  # longitude: 170°W to 30°W\n      ylim = c(-60, 85),    # latitude: South to North America\n      expand = FALSE\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/main-character-question-C-2-2.png){width=2100}\n:::\n\n```{.r .cell-code}\nC_mod |> gf_sf(geometry = ~ geometry, fill = ~ pop) |>\n  gf_refine(\n    coord_sf(\n      xlim = c(-170, -30),  # longitude: 170°W to 30°W\n      ylim = c(-60, 85),    # latitude: South to North America\n      expand = FALSE\n    )\n  )\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/main-character-question-C-2-3.png){width=2100}\n:::\n:::\n\n\n\n\n### 6. Say\n\n~~Caption + one sentence we will stand behind.~~\n\nAcross the Americas, based on 2007 data from `gapminder`, `lifeExp`ectancy and `gdpPercap` are positively correlated (correlation coefficient = 0.59, p-value < 0.05).\n\nThe correlation would perhaps even be higher, if we left out a few high `gddperCap` countries since these are clearly outliers with a huge amount of `leverage`. ( Which countries are these?)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nC_mod_2 <- C_mod |> \n  filter(!gdpPercap >= 15000)\nC_mod_2\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"\"],\"name\":[\"_rn_\"],\"type\":[\"\"],\"align\":[\"left\"]},{\"label\":[\"country\"],\"name\":[1],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"continent\"],\"name\":[2],\"type\":[\"fct\"],\"align\":[\"left\"]},{\"label\":[\"year\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"lifeExp\"],\"name\":[4],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"pop\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"gdpPercap\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"geometry\"],\"name\":[7],\"type\":[\"s_MULTIP\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"Argentina\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"75.320\",\"5\":\"40301927\",\"6\":\"12779.380\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"1\"},{\"1\":\"Bolivia\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"65.554\",\"5\":\"9119152\",\"6\":\"3822.137\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"2\"},{\"1\":\"Brazil\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"72.390\",\"5\":\"190010647\",\"6\":\"9065.801\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"3\"},{\"1\":\"Chile\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"78.553\",\"5\":\"16284741\",\"6\":\"13171.639\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"4\"},{\"1\":\"Colombia\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"72.889\",\"5\":\"44227550\",\"6\":\"7006.580\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"5\"},{\"1\":\"Costa Rica\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"78.782\",\"5\":\"4133884\",\"6\":\"9645.061\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"6\"},{\"1\":\"Cuba\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"78.273\",\"5\":\"11416987\",\"6\":\"8948.103\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"7\"},{\"1\":\"Dominican Republic\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"72.235\",\"5\":\"9319622\",\"6\":\"6025.375\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"8\"},{\"1\":\"Ecuador\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"74.994\",\"5\":\"13755680\",\"6\":\"6873.262\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"9\"},{\"1\":\"El Salvador\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"71.878\",\"5\":\"6939688\",\"6\":\"5728.354\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"10\"},{\"1\":\"Guatemala\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"70.259\",\"5\":\"12572928\",\"6\":\"5186.050\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"11\"},{\"1\":\"Haiti\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"60.916\",\"5\":\"8502814\",\"6\":\"1201.637\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"12\"},{\"1\":\"Honduras\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"70.198\",\"5\":\"7483763\",\"6\":\"3548.331\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"13\"},{\"1\":\"Jamaica\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"72.567\",\"5\":\"2780132\",\"6\":\"7320.880\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"14\"},{\"1\":\"Mexico\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"76.195\",\"5\":\"108700891\",\"6\":\"11977.575\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"15\"},{\"1\":\"Nicaragua\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"72.899\",\"5\":\"5675356\",\"6\":\"2749.321\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"16\"},{\"1\":\"Panama\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"75.537\",\"5\":\"3242173\",\"6\":\"9809.186\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"17\"},{\"1\":\"Paraguay\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"71.752\",\"5\":\"6667147\",\"6\":\"4172.838\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"18\"},{\"1\":\"Peru\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"71.421\",\"5\":\"28674757\",\"6\":\"7408.906\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"19\"},{\"1\":\"Uruguay\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"76.384\",\"5\":\"3447496\",\"6\":\"10611.463\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"20\"},{\"1\":\"Venezuela\",\"2\":\"Americas\",\"3\":\"2007\",\"4\":\"73.747\",\"5\":\"26084662\",\"6\":\"11415.806\",\"7\":\"<s_MULTIP>\",\"_rn_\":\"21\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n\n```{.r .cell-code}\nC_mod_2 |> gf_point(lifeExp ~ gdpPercap) |> gf_smooth(method = \"lm\")\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/unnamed-chunk-1-1.png){width=2100}\n:::\n\n```{.r .cell-code}\nmosaic::cor.test(lifeExp ~ gdpPercap, \n                 data = C_mod_2) |> \n  broom::tidy()\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"estimate\"],\"name\":[1],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"statistic\"],\"name\":[2],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"p.value\"],\"name\":[3],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"parameter\"],\"name\":[4],\"type\":[\"int\"],\"align\":[\"right\"]},{\"label\":[\"conf.low\"],\"name\":[5],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"conf.high\"],\"name\":[6],\"type\":[\"dbl\"],\"align\":[\"right\"]},{\"label\":[\"method\"],\"name\":[7],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"alternative\"],\"name\":[8],\"type\":[\"chr\"],\"align\":[\"left\"]}],\"data\":[{\"1\":\"0.7805573\",\"2\":\"5.443059\",\"3\":\"2.984187e-05\",\"4\":\"19\",\"5\":\"0.5261652\",\"6\":\"0.9067193\",\"7\":\"Pearson's product-moment correlation\",\"8\":\"two.sided\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\n\nThe maps show the disparity in all the three quant variables across the Americas. Interestingly, the USA and Brazil turn out to have the highest populations, while Canada and other South American coutries are lower on the `pop` scale. \n\n### 7. Limit\n\n~~What this panel cannot do.~~\n\nSpeak of trade or of aid!\nNor speak of Asia.\nNor of variations over TIME!\n\n\n# Panel D — Found Data\n\n????\n\n\n# Conclusion\n\n- The question we will defend in ninety seconds\n- What we will **not** claim\n- Which lines were human, which were machine\n- Limits\n- Gift for the steal-this strip\n",
    "supporting": [
      "studio-wall_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}