{
  "hash": "3c7d0cac0348a5439b34398e5994283e",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Group 2 — Risk factors\"\nsubtitle: \"Studio wall\"\nauthor: \"Group names here\"\nformat:\n  html:\n    toc: true\n    toc-depth: 2\n---\n\n# Spine\n\n> How do bodies carry risk, how do class and smoke talk, and where do children still die young?\n\nThis sentence stays at the top. Every panel must attach to it. If a plot cannot be introduced in a clause that hangs off this line, it is off the wall.\n\n# Introduction — the tables we own\n\nThis folder is ours for the ten days. Three tables, three shapes.\n\n- **Panel A** (`panel-A.csv`) — `cardioRiskFactors`: BMI, lipids, blood pressure, uric acid. `sex` and `smok` have already been recoded from integers to factors.\n- **Panel B** (`panel-B.csv`) — Scottish Health Survey 1998: sex, social class, smoking, diagnosed CVD. `area` is a code, not a map.\n- **Panel C** (`panel-C.csv`) — SOWC child / infant / neonatal mortality by country. Join by country name.\n\nIf a brick needs a histogram, it lives in A. If it needs a mosaic, it lives in B.\n\nWe load from this folder:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(mosaic)\nlibrary(skimr)\nlibrary(ggformula)\n##\nlibrary(vcd) # for Panel B\n\n\nA <- read_csv(\"../../../data/group-2-risk-factors/panel-A.csv\")\nB <- read_csv(\"../../../data/group-2-risk-factors/panel-B.csv\")\nC <- read_csv(\"../../../data/group-2-risk-factors/panel-C.csv\")\n```\n:::\n\n\n~Found tables train the mark. A campus Free Hunch, if we collect one, is a **made** panel of the same pair type — new people, old grammar. It does not replace A, B, or C.~\n\n# Panel A — body / measure\n\n*bmi, choles, sys, dia, Uric are Quant. Do not average `smok`.*\n\n\n### 1. See the table\n\nWhat is a case? Which columns are Quant / Qual? What is missing?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# glimpse() / inspect() / skim()\ndplyr::glimpse(A)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 998\nColumns: 14\n$ age      <dbl> 52, 54, 61, 51, 58, 62, 54, 52, 45, 55, 39, 57, 31, 50, 50, 4…\n$ bmi      <dbl> 36.9, 30.7, 32.2, 36.6, 31.4, 42.3, 26.7, 27.0, 34.0, 20.9, 2…\n$ waisthip <dbl> 0.8000000, 0.8256881, 0.8653846, 0.9166667, 0.8269231, 0.9391…\n$ smok     <chr> \"non_smoker\", \"non_smoker\", \"non_smoker\", \"non_smoker\", \"non_…\n$ choles   <dbl> 7.4, 7.9, 7.0, 5.7, 8.7, 8.1, 6.5, 7.7, 7.4, 6.7, 7.4, 5.5, 4…\n$ trig     <dbl> 3.44, 2.24, 1.75, 2.10, 2.26, 1.97, 2.64, 2.07, 2.63, 2.99, 3…\n$ hdl      <dbl> 1.25, 1.46, 1.28, 1.07, 0.80, 1.02, 1.66, 1.18, 0.84, 1.11, 1…\n$ ldl      <dbl> 4.59, 5.42, 4.92, 3.68, 6.87, 6.18, 3.64, 5.58, 5.36, 4.23, 4…\n$ sys      <dbl> 154, 135, 154, 180, 154, 116, 168, 156, 141, 156, 141, 135, 1…\n$ dia      <dbl> 89.0, 81.0, 93.0, 112.0, 104.0, 85.0, 105.0, 104.0, 77.0, 96.…\n$ Uric     <dbl> 437, 361, 268, 335, 549, 315, 903, 691, 304, 607, 366, 482, 2…\n$ sex      <chr> \"female\", \"female\", \"female\", \"female\", \"female\", \"female\", \"…\n$ alco     <dbl> 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 208.285…\n$ apoa     <dbl> 1.47, 1.18, 1.32, 1.07, 1.14, 1.08, 1.41, 1.19, 0.85, 1.27, 1…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA_mod <- A |> mutate(\n  sex = as.factor(sex),\n  smok = as.factor(smok)) |> \n  \n  select(sex, smok, everything()) # factors first\n\nglimpse(A_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 998\nColumns: 14\n$ sex      <fct> female, female, female, female, female, female, male, male, f…\n$ smok     <fct> non_smoker, non_smoker, non_smoker, non_smoker, non_smoker, n…\n$ age      <dbl> 52, 54, 61, 51, 58, 62, 54, 52, 45, 55, 39, 57, 31, 50, 50, 4…\n$ bmi      <dbl> 36.9, 30.7, 32.2, 36.6, 31.4, 42.3, 26.7, 27.0, 34.0, 20.9, 2…\n$ waisthip <dbl> 0.8000000, 0.8256881, 0.8653846, 0.9166667, 0.8269231, 0.9391…\n$ choles   <dbl> 7.4, 7.9, 7.0, 5.7, 8.7, 8.1, 6.5, 7.7, 7.4, 6.7, 7.4, 5.5, 4…\n$ trig     <dbl> 3.44, 2.24, 1.75, 2.10, 2.26, 1.97, 2.64, 2.07, 2.63, 2.99, 3…\n$ hdl      <dbl> 1.25, 1.46, 1.28, 1.07, 0.80, 1.02, 1.66, 1.18, 0.84, 1.11, 1…\n$ ldl      <dbl> 4.59, 5.42, 4.92, 3.68, 6.87, 6.18, 3.64, 5.58, 5.36, 4.23, 4…\n$ sys      <dbl> 154, 135, 154, 180, 154, 116, 168, 156, 141, 156, 141, 135, 1…\n$ dia      <dbl> 89.0, 81.0, 93.0, 112.0, 104.0, 85.0, 105.0, 104.0, 77.0, 96.…\n$ Uric     <dbl> 437, 361, 268, 335, 549, 315, 903, 691, 304, 607, 366, 482, 2…\n$ alco     <dbl> 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 0.00000, 208.285…\n$ apoa     <dbl> 1.47, 1.18, 1.32, 1.07, 1.14, 1.08, 1.41, 1.19, 0.85, 1.27, 1…\n```\n\n\n:::\n:::\n\nMy Panel-A data has:\n\n  - 998 observations and 11 variables\n  - `smok`, `sex` are Qual variables\n  - `bmi`, `waisthip`, `choles`, `ldl`, `hdl`, `sys`, `dia`, `Uric`, `alco`, and `apoa` are Quant variables\n  \n### 2. Ask\n\n~~One question *this* table can answer. One it cannot. Write both.~~\n\nLooking at the spine statement, I can pose the following Questions:\n\nPossibly can answer: \n\n1. Are the dataset balanced by `sex` and by `smok` ?\n1. What are the distributions for each of the Quant variables?\n1. How are they different based on the Qual variables? Is there any risk ( Quant variable) that is different based on `sex` or `smok`?\n\nPossibly cannot answer:\n\n1. There is no data on disease or other symptoms, so cannot plot that. \n\n### 3. Choose a mark\n\n~Geom, map mark, or (later) test that matches the pair type. Name it before you code.~\n\n- Bar Charts\n- Histograms\n- Histograms with fill\n- Boxplots for variety\n\n### 4. Predict\n\nWhat do we think we will see? One sentence, before Run.\n\n### 5. Make\n\nHuman brick first. Optional: one AI prompt, pasted below, only for what section 3 named.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Question 1\nA_mod |> gf_histogram(~ bmi)\nA_mod |> gf_histogram(~ waisthip)\nA_mod |> gf_histogram(~ choles)\nA_mod |> gf_histogram(~ ldl)\nA_mod |> gf_histogram(~ hdl)\nA_mod |> gf_histogram(~ sys)\nA_mod |> gf_histogram(~ dia)\nA_mod |> gf_histogram(~ Uric)\nA_mod |> gf_histogram(~ alco)\nA_mod |> gf_histogram(~ apoa)\n\n## Question 2\nA_mod |> gf_histogram(~ choles, fill = ~ sex)\nA_mod |> gf_histogram(~ choles, fill = ~ smok)\nA_mod |> gf_histogram(~ ldl, fill = ~ sex)\nA_mod |> gf_histogram(~ ldl, fill = ~ smok)\nA_mod |> gf_histogram(~ hdl, fill = ~ sex)\nA_mod |> gf_histogram(~ hdl, fill = ~ smok)\nA_mod |> gf_histogram(~ sys, fill = ~ sex)\nA_mod |> gf_histogram(~ sys, fill = ~ smok)\nA_mod |> gf_histogram(~ dia, fill = ~ sex)\nA_mod |> gf_histogram(~ dia, fill = ~ smok)\nA_mod |> gf_histogram(~ alco, fill = ~ sex)\nA_mod |> gf_histogram(~ alco, fill = ~ smok)\nA_mod |> gf_histogram(~ apoa, fill = ~ sex)\nA_mod |> gf_histogram(~ apoa, fill = ~ smok)\n## Just for variety\nA_mod |> gf_boxplot(sex ~ apoa, fill = ~ sex)\nA_mod |> gf_boxplot(smok ~ apoa, fill = ~ smok)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nA_mod |> gf_histogram(~ Uric, fill = ~ sex)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/unnamed-chunk-2-1.png){width=2100}\n:::\n\n```{.r .cell-code}\nA_mod |> gf_histogram(~ Uric, fill = ~ smok)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\n`stat_bin()` using `bins = 30`. Pick better value `binwidth`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/unnamed-chunk-2-2.png){width=2100}\n:::\n:::\n\n\n### 6. Say\n\n`Uric` acid distributions look wild! There is so much right-skew to that distribution; the max value is near 2000! Someone suffers from a serious case of gout!\n\n\n### 7. Limit\n\n~What this panel cannot do. Which kit table we refused to abuse.~\n\nCan only speak of general conditions and their risks. Cannot actually say that the risk has manifested!\n\n\n# Panel B — category / talk\n\n*smoke × sex, cvd × sc (social class). `area` is forbidden as geography.*\n\n\n### 1. See the table\n\nWhat is a case? Which columns are Quant / Qual? What is missing?\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# glimpse() / inspect() / skim()\ndplyr::glimpse(B)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8,804\nColumns: 7\n$ age      <dbl> 50, 71, 55, 61, 32, 26, 68, 32, 20, 37, 47, 37, 70, 34, 49, 4…\n$ sex      <chr> \"female\", \"female\", \"female\", \"female\", \"female\", \"female\", \"…\n$ sc       <dbl> 3, 45, 45, 3, 12, 3, 45, 12, 45, 12, 12, 45, 12, 3, 3, 12, 3,…\n$ carstair <dbl> -2.45, -2.45, -2.45, -2.45, -2.45, -2.45, -2.45, -2.45, -2.45…\n$ smoke    <chr> \"nevr\", \"nevr\", \"mod\", \"ex\", \"ex\", \"mod\", \"hvy\", \"nevr\", \"ex\"…\n$ area     <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n$ cvd      <chr> \"no\", \"no\", \"no\", \"yes\", \"no\", \"no\", \"yes\", \"yes\", \"no\", \"no\"…\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB_mod <- B |> \n  mutate(across(where(is.character), as_factor)) |> \n  select(sex, cvd, smoke, everything()) # factors first\n\nglimpse(B_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8,804\nColumns: 7\n$ sex      <fct> female, female, female, female, female, female, female, male,…\n$ cvd      <fct> no, no, no, yes, no, no, yes, yes, no, no, no, no, no, no, no…\n$ smoke    <fct> nevr, nevr, mod, ex, ex, mod, hvy, nevr, ex, ex, nevr, ex, ne…\n$ age      <dbl> 50, 71, 55, 61, 32, 26, 68, 32, 20, 37, 47, 37, 70, 34, 49, 4…\n$ sc       <dbl> 3, 45, 45, 3, 12, 3, 45, 12, 45, 12, 12, 45, 12, 3, 3, 12, 3,…\n$ carstair <dbl> -2.45, -2.45, -2.45, -2.45, -2.45, -2.45, -2.45, -2.45, -2.45…\n$ area     <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n```\n\n\n:::\n\n```{.r .cell-code}\nB |> count(smoke) # What are the levels?\n```\n\n::: {.cell-output-display}\n`````{=html}\n<div data-pagedtable=\"false\">\n  <script data-pagedtable-source type=\"application/json\">\n{\"columns\":[{\"label\":[\"smoke\"],\"name\":[1],\"type\":[\"chr\"],\"align\":[\"left\"]},{\"label\":[\"n\"],\"name\":[2],\"type\":[\"int\"],\"align\":[\"right\"]}],\"data\":[{\"1\":\"ex\",\"2\":\"2151\"},{\"1\":\"hvy\",\"2\":\"1233\"},{\"1\":\"lite\",\"2\":\"577\"},{\"1\":\"mod\",\"2\":\"1270\"},{\"1\":\"nevr\",\"2\":\"3573\"}],\"options\":{\"columns\":{\"min\":{},\"max\":[10]},\"rows\":{\"min\":[10],\"max\":[10]},\"pages\":{}}}\n  </script>\n</div>\n`````\n:::\n:::\n\n\nMy Panel-B data has:\n\n- 8804 observations with 7 variables\n- `sex`, `cvd`, `smoke` are Qual variables\n-  `age` is Quant variable ( Age in years)\n- `sc` is social class, encoded as Quant\n- `carstair` is Quant variable, meaning not clear, perhaps related to exercise\n\n\n::: {.cell}\n\n```{.r .cell-code}\nskimr::skim(B_mod)\n```\n\n::: {.cell-output-display}\n\nTable: Data summary\n\n|                         |      |\n|:------------------------|:-----|\n|Name                     |B_mod |\n|Number of rows           |8804  |\n|Number of columns        |7     |\n|_______________________  |      |\n|Column type frequency:   |      |\n|factor                   |3     |\n|numeric                  |4     |\n|________________________ |      |\n|Group variables          |None  |\n\n\n**Variable type: factor**\n\n|skim_variable | n_missing| complete_rate|ordered | n_unique|top_counts                                |\n|:-------------|---------:|-------------:|:-------|--------:|:-----------------------------------------|\n|sex           |         0|             1|FALSE   |        2|fem: 4987, mal: 3817                      |\n|cvd           |         0|             1|FALSE   |        2|no: 6389, yes: 2415                       |\n|smoke         |         0|             1|FALSE   |        5|nev: 3573, ex: 2151, mod: 1270, hvy: 1233 |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|   mean|    sd|    p0|   p25|    p50|    p75|   p100|hist  |\n|:-------------|---------:|-------------:|------:|-----:|-----:|-----:|------:|------:|------:|:-----|\n|age           |         0|             1|  46.21| 15.52| 18.00| 33.00|  45.00|  60.00|  74.00|▆▇▆▆▆ |\n|sc            |         0|             1|  18.34| 18.09|  3.00|  3.00|  12.00|  45.00|  45.00|▇▅▁▁▆ |\n|carstair      |         0|             1|  -0.20|  3.27| -6.23| -2.46|  -0.68|   1.48|  12.53|▅▇▃▁▁ |\n|area          |         0|             1| 162.75| 91.19|  1.00| 84.00| 165.00| 244.25| 312.00|▆▆▇▇▇ |\n\n\n:::\n:::\n\nFurther, on the Qual variables panel-B data has : \n\n- `sex` has 2 levels: \"mal\" and \"fem\"\n- `cvd` has 2 levels: \"no\" and \"yes\"\n- `smoke` has 3 levels: \"nev\", \"lite\", \"mod\", \"hvy\", \"ex\". Need to make this into an ordered factor!\n\nAnd on the Quant variables panel-B data has :\n\n- `age` has a mean of 45.26, sd of 13.2, median of 45, min of 19, and max of 90\n- `sc` has a mean of 18.34, sd of 18.092, median of 12, min of 3, and max of 45\n- `carstair` has a mean of -0.20, sd of 3.26, median of -0.68, min of -6.23, and max of 12.53\n- `area` has a mean of 162, sd of 91, median of 165, min of 1, and max of 312. \n\nThere is no missing data. All histograms look uniform!!\n\n\n::: {.cell}\n\n```{.r .cell-code}\nB_mod <- B_mod |> \n  mutate(smoke = base::factor(smoke, \n                              levels = c(\"nevr\", \"lite\", \"mod\", \"hvy\", \"ex\"), \n                              ordered = TRUE))\nglimpse(B_mod)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nRows: 8,804\nColumns: 7\n$ sex      <fct> female, female, female, female, female, female, female, male,…\n$ cvd      <fct> no, no, no, yes, no, no, yes, yes, no, no, no, no, no, no, no…\n$ smoke    <ord> nevr, nevr, mod, ex, ex, mod, hvy, nevr, ex, ex, nevr, ex, ne…\n$ age      <dbl> 50, 71, 55, 61, 32, 26, 68, 32, 20, 37, 47, 37, 70, 34, 49, 4…\n$ sc       <dbl> 3, 45, 45, 3, 12, 3, 45, 12, 45, 12, 12, 45, 12, 3, 3, 12, 3,…\n$ carstair <dbl> -2.45, -2.45, -2.45, -2.45, -2.45, -2.45, -2.45, -2.45, -2.45…\n$ area     <dbl> 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1…\n```\n\n\n:::\n:::\n\n\n\n### 2. Ask\n\n~~One question *this* table can answer. One it cannot. Write both.~~\nLooking at the spine statement, I can pose the following Questions:\n\nPossibly can answer: \n\n1. Are the dataset balanced by `sex`, `cvd`, and `smoke`? \n1. Are `cvd` and `smoke` associated? (Main Character Question)\n1. Are `cvd` and `sc` associated ? ( Also Main Character Question)\n\nPossibly cannot answer:\n\n1. Whether `smoke`-ing CAUSES `cvd`? Why not??\n\n### 3. Choose a mark\n\n~~Geom, map mark, or (later) test that matches the pair type. Name it before you code.~~\n\n1. Bar charts\n2. Mosaic Charts(NEW!)\n\n### 4. Predict\n\n~What do we think we will see? One sentence, before Run.~\nI expect to see `cvd` worsen with `smoke`ing. `sc` may be curiously associated with `cvd` but may be confounded by `smoke`ing.\n\n\n### 5. Make\n\n~~Human brick first. Optional: one AI prompt, pasted below, only for what section 3 named.~~\n\n\n::: {.cell}\n\n```{.r .cell-code}\n## Question 1\nB_mod |> gf_bar(~ cvd)\nB_mod |> gf_bar(~ sc)\nB_mod |> gf_bar(~ sex)\n```\n:::\n\n\n`sc` is not really balanced at all, nor is `sex`.\n\n`cvd` is not balanced, but it is an output variable. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Question #2\nsccvd_table <- vcd::structable(sc ~ cvd, data = B_mod)\nsccvd_table\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    sc    3   12   45\ncvd                  \nno     2661 1800 1928\nyes    1025  621  769\n```\n\n\n:::\n\n```{.r .cell-code}\nsmokecvd_tab <- vcd::structable(smoke ~ cvd, data = B_mod)\nsmokecvd_tab\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    smoke nevr lite  mod  hvy   ex\ncvd                               \nno        2701  434  968  910 1376\nyes        872  143  302  323  775\n```\n\n\n:::\n\n```{.r .cell-code}\n##\nvcd::mosaic(sccvd_table, shade = TRUE, legend = TRUE, main = \"Mosaic of social class vs CVD\", sub = \"Actual\")\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/main-character-question-B-1.png){width=2100}\n:::\n\n```{.r .cell-code}\nvcd::mosaic(sccvd_table, shade = TRUE, legend = TRUE, main = \"Mosaic of social class vs CVD\", sub = \"Expected\", type = \"expected\")\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/main-character-question-B-2.png){width=2100}\n:::\n\n```{.r .cell-code}\nvcd::mosaic(smokecvd_tab, shade = TRUE, legend = TRUE, main = \"Mosaic of smoking vs CVD\", sub = \"Actual\")\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/main-character-question-B-3.png){width=2100}\n:::\n\n```{.r .cell-code}\nvcd::mosaic(smokecvd_tab, shade = TRUE, legend = TRUE, main = \"Mosaic of smoking vs CVD\", sub = \"Expected\", type = \"expected\")\n```\n\n::: {.cell-output-display}\n![](studio-wall_files/figure-html/main-character-question-B-4.png){width=2100}\n:::\n:::\n\n\n### 6. Say\n\n~~Caption + one sentence we will stand behind. Title is a sentence, not a column name.~~\n\nSmoking and Cardio-Vascular Disease are definitely associated, with a p-value of <2.22e-16!!\n\n### 7. Limit\n\n~~What this panel cannot do. Which kit table we refused to abuse.~~\n\nCan't PROVE that smoking causes cancer, since this is not an RCT Table!!\n\n# Panel C — place\n\n*under5_mortality_2018 and infant_mortality_2018 are rates. Join on `country`.*\n\nGeometry is not in the CSV. Join in R, then use the same seven headings.\n\n```r\n# library(sf)\n# library(rnaturalearth)\n# world <- ne_countries(scale = \"medium\", returnclass = \"sf\")\n# # join on country name; list the unmatched labels\n```\n\n\n### 1. See the table\n\nWhat is a case? Which columns are Quant / Qual? What is missing?\n\n```r\n# glimpse() / inspect() / skim()\n```\n\n### 2. Ask\n\nOne question *this* table can answer. One it cannot. Write both.\n\n### 3. Choose a mark\n\nGeom, map mark, or (later) test that matches the pair type. Name it before you code.\n\n### 4. Predict\n\nWhat do we think we will see? One sentence, before Run.\n\n### 5. Make\n\nHuman brick first. Optional: one AI prompt, pasted below, only for what section 3 named.\n\n```r\n# human chunk\n\n# ## Prompt we actually used\n# ai_draft\n# ours\n```\n\n### 6. Say\n\nCaption + one sentence we will stand behind. Title is a sentence, not a column name.\n\n### 7. Limit\n\nWhat this panel cannot do. Which kit table we refused to abuse.\n\n\n# Conclusion\n\nWhat the spine looks like after three panels.\n\n- The question we will defend in ninety seconds\n- What we will **not** claim\n- Which lines were human, which were machine\n- Limits: sample, missingness, the test we did not run\n- Gift for the steal-this strip (palette, annotation, join trick)\n\n```r\n# sessionInfo()\n```\n",
    "supporting": [
      "studio-wall_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-in-header": [
        "<link href=\"../../../site_libs/pagedtable-1.1/css/pagedtable.css\" rel=\"stylesheet\" />\n<script src=\"../../../site_libs/pagedtable-1.1/js/pagedtable.js\"></script>\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}